### PR TITLE
Don't enable the plugin if buidlerevm net is used

### PR DESCRIPTION
**Pull request by alcuadrado**
Hey @cgewecke,

I was just helping someone debug a problem with this plugin, and thought that this change would make things easier for most of its users.

TBH, I haven't tested it, and coded it directly here, so the implementation can be wrong 😅 I thought it was good way to showing the idea though.

Best
Pato

### CODE REVIEW

**Comment by cgewecke** [comment]
Thanks Patricio! LGTM.

**Comment by alcuadrado** [comment]
Hey Chris, any plan to release this soon? This is a very frequent problem for unexperienced users.

**Comment by cgewecke** [comment]
@alcuadrado Sorry...

All the work's been done (PR #20) to get the gas-reporter to run with BuidlerEVM itself (which is preferable I think because much faster etc). Synthetix and MStable are both using a beta version of that and it seems ok. 

However, #20 has a bug with Ethers backed providers - I'll try to fix that today and either publish the beta, or if unlucky, publish this PR.

**Comment by alcuadrado** [comment]
Ohh! I didn't know that! That's awesome!

**Pull request merged**
